/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class Admin_Login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login
     */
    public Admin_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        lbALog1 = new java.awt.Label();
        buttadminLogintoStudent = new javax.swing.JButton();
        buttHomeAdmin = new javax.swing.JButton();
        buttadminLogintoTentor = new javax.swing.JButton();
        tf_adminLogin1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttadminLoginBackHome = new javax.swing.JButton();
        tf_adminLogin2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Login Page E-Learning System ");

        jPanel2.setBackground(new java.awt.Color(31, 40, 51));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        lbALog1.setAlignment(java.awt.Label.CENTER);
        lbALog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog1.setForeground(new java.awt.Color(255, 153, 0));
        lbALog1.setText("Selamat Datang Admin");

        buttadminLogintoStudent.setBackground(new java.awt.Color(204, 204, 204));
        buttadminLogintoStudent.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttadminLogintoStudent.setText("MAHASISWA");
        buttadminLogintoStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttadminLogintoStudentActionPerformed(evt);
            }
        });

        buttHomeAdmin.setBackground(new java.awt.Color(204, 204, 204));
        buttHomeAdmin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttHomeAdmin.setText("LOGIN");
        buttHomeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHomeAdminActionPerformed(evt);
            }
        });

        buttadminLogintoTentor.setBackground(new java.awt.Color(204, 204, 204));
        buttadminLogintoTentor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttadminLogintoTentor.setText("DOSEN");
        buttadminLogintoTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttadminLogintoTentorActionPerformed(evt);
            }
        });

        tf_adminLogin1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_adminLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_adminLogin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("USERNAME ");

        buttadminLoginBackHome.setBackground(new java.awt.Color(204, 204, 204));
        buttadminLoginBackHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttadminLoginBackHome.setText("HOME");
        buttadminLoginBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttadminLoginBackHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttadminLogintoTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(buttadminLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(buttadminLogintoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttHomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_adminLogin2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_adminLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(189, 189, 189))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_adminLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_adminLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(buttHomeAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttadminLogintoTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttadminLogintoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttadminLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttadminLogintoStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttadminLogintoStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttadminLogintoStudentActionPerformed

    private void buttHomeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHomeAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttHomeAdminActionPerformed

    private void buttadminLogintoTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttadminLogintoTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttadminLogintoTentorActionPerformed

    private void tf_adminLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_adminLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_adminLogin1ActionPerformed

    private void buttadminLoginBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttadminLoginBackHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttadminLoginBackHomeActionPerformed

    //get Textfield
    public String gettf_adminLogin1(){
        return tf_adminLogin1.getText();
    }
    
    public String gettf_adminLogin2(){
        return tf_adminLogin2.getText();
    }
    
    //getJButton
    public JButton getbuttHomeAdmin(){
        return buttHomeAdmin;
    }
    public JButton getbuttadminLoginBackHome(){
        return buttadminLoginBackHome;
    }
    public JButton getbuttadminLogintoStudent(){
        return buttadminLogintoStudent;
    }
    public JButton getbuttadminLogintoTentor(){
        return buttadminLogintoTentor;
    }
    
    //Listener and Adapter
    public void Listener(ActionListener AL){
        buttHomeAdmin.addActionListener(AL);
        buttadminLoginBackHome.addActionListener(AL);
        buttadminLogintoStudent.addActionListener(AL);
        buttadminLogintoTentor.addActionListener(AL);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttHomeAdmin;
    private javax.swing.JButton buttadminLoginBackHome;
    private javax.swing.JButton buttadminLogintoStudent;
    private javax.swing.JButton buttadminLogintoTentor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label lbALog1;
    private javax.swing.JTextField tf_adminLogin1;
    private javax.swing.JPasswordField tf_adminLogin2;
    // End of variables declaration//GEN-END:variables
}
