/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
/**
 *
 * @author Asus
 */
public class Admin_viewKelasStudentTentor extends javax.swing.JFrame {

    /**
     * Creates new form Admin_viewKelasStudentTentor
     */
    public Admin_viewKelasStudentTentor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttbacktoAdminMenu = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKelas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStudent = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTentor = new javax.swing.JList<>();
        buttTampilStudent = new javax.swing.JButton();
        buttTampilKelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));

        buttbacktoAdminMenu.setBackground(new java.awt.Color(204, 204, 204));
        buttbacktoAdminMenu.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttbacktoAdminMenu.setText("BACK");
        buttbacktoAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttbacktoAdminMenuActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Admin Page E-Learning System ");

        jScrollPane1.setViewportView(listKelas);

        jScrollPane2.setViewportView(listStudent);

        jScrollPane3.setViewportView(listTentor);

        buttTampilStudent.setBackground(new java.awt.Color(204, 204, 204));
        buttTampilStudent.setText("Tampil");

        buttTampilKelas.setBackground(new java.awt.Color(204, 204, 204));
        buttTampilKelas.setText("Tampil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttbacktoAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttTampilKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(buttTampilStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttTampilStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttTampilKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(buttbacktoAdminMenu)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttbacktoAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttbacktoAdminMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttbacktoAdminMenuActionPerformed

    public JButton getbuttbacktoAdminMenu(){
        return buttbacktoAdminMenu;
    }

    public JButton getButtTampilKelas() {
        return buttTampilKelas;
    }

    public JButton getButtTampilStudent() {
        return buttTampilStudent;
    }
    
    
     public void listenerTentorViewKelasStudent(ActionListener AL){
       buttbacktoAdminMenu.addActionListener(AL);
       buttTampilKelas.addActionListener(AL);
       buttTampilStudent.addActionListener(AL);
    }
    public void mouseAdapter(MouseAdapter ma){
        listKelas.addMouseListener(ma);
        listStudent.addMouseListener(ma);
        listTentor.addMouseListener(ma);
    }
    public void setListKelas(String [] listId){
       listKelas.setListData(listId);
    }
    public void setListStudent(String [] listId){
       listStudent.setListData(listId);
    }
    public void setListTentor(String [] listId){
       listTentor.setListData(listId);
    }
    
    
    public String getSelectedKelas(){
        return listKelas.getSelectedValue();
    }
    public String getSelectedTentor(){
        return listTentor.getSelectedValue();
    }

    public JList getJlist_Kelas() {
        return listKelas;
    }
    public JList getJlist_Tentor() {
        return listTentor;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttTampilKelas;
    private javax.swing.JButton buttTampilStudent;
    private javax.swing.JButton buttbacktoAdminMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private javax.swing.JList<String> listKelas;
    private javax.swing.JList<String> listStudent;
    private javax.swing.JList<String> listTentor;
    // End of variables declaration//GEN-END:variables
}
