/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import Database.Database;
import eLearning.*;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class Student_register extends javax.swing.JFrame {

    /**
     * Creates new form Student_register
     */
    public Student_register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        label1 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        lbALog4 = new java.awt.Label();
        buttstudentLoginToAdmin3 = new javax.swing.JButton();
        buttstudentLogintoTentor3 = new javax.swing.JButton();
        tf_studentRegUsername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        buttstudentLoginBackHome3 = new javax.swing.JButton();
        buttHomeStudent = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_studentRegPass = new javax.swing.JPasswordField();
        tf_studentRegID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_studentRegName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Login Page E-Learning System ");

        jPanel5.setBackground(new java.awt.Color(31, 40, 51));
        jPanel5.setForeground(new java.awt.Color(255, 204, 0));

        lbALog4.setAlignment(java.awt.Label.CENTER);
        lbALog4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog4.setForeground(new java.awt.Color(255, 153, 0));
        lbALog4.setText("Registrasi Mahasiswa");

        buttstudentLoginToAdmin3.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLoginToAdmin3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLoginToAdmin3.setText("ADMIN");
        buttstudentLoginToAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLoginToAdmin3ActionPerformed(evt);
            }
        });

        buttstudentLogintoTentor3.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLogintoTentor3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLogintoTentor3.setText("DOSEN");
        buttstudentLogintoTentor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLogintoTentor3ActionPerformed(evt);
            }
        });

        tf_studentRegUsername.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_studentRegUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_studentRegUsernameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("PASSWORD");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("USERNAME ");

        buttstudentLoginBackHome3.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLoginBackHome3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLoginBackHome3.setText("HOME");
        buttstudentLoginBackHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLoginBackHome3ActionPerformed(evt);
            }
        });

        buttHomeStudent.setBackground(new java.awt.Color(204, 204, 204));
        buttHomeStudent.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttHomeStudent.setText("SIGN UP");
        buttHomeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHomeStudentActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("NAMA ");

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("ID SISWA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttstudentLogintoTentor3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(buttstudentLoginBackHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(buttstudentLoginToAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lbALog4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_studentRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_studentRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_studentRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_studentRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(buttHomeStudent)
                        .addGap(165, 165, 165))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbALog4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_studentRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_studentRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_studentRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_studentRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(buttHomeStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttstudentLogintoTentor3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttstudentLoginToAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttstudentLoginBackHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttstudentLoginToAdmin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLoginToAdmin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLoginToAdmin3ActionPerformed

    private void buttstudentLogintoTentor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLogintoTentor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLogintoTentor3ActionPerformed

    private void tf_studentRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_studentRegUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_studentRegUsernameActionPerformed

    private void buttstudentLoginBackHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLoginBackHome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLoginBackHome3ActionPerformed

    private void buttHomeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHomeStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttHomeStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //get Button
    public JButton getButtSignUp(){
        return buttHomeStudent;
    }
    public JButton getbuttstudentLoginBackHome(){
        return buttstudentLoginBackHome3;
    }
    public JButton getbutttentorLogintoAdmin(){
        return buttstudentLoginToAdmin3;
    }
    public JButton getbuttstudentLogintoStudent(){
        return buttstudentLogintoTentor3;
    }
    
    //get Text
    public String gettf_studentRegName(){
        return tf_studentRegName.getText();
    }
    public String gettf_studentRegUsername(){
        return tf_studentRegUsername.getText();
    }
    public String gettf_studentRegPass(){
        return tf_studentRegPass.getText();
    }
    public String getTf_studentRegID() {
        return tf_studentRegID.getText();
    }
    
    
    //setDaftar
    public void daftarStudent(){
        Database db = new Database();
        db.connect();
        String name = gettf_studentRegName();
        int umur = 0;
        String idKelas = getTf_studentRegID();
        String uname = gettf_studentRegUsername();
        String pass = gettf_studentRegPass();
        Student s = new Student(name,umur,idKelas,uname,pass);
        db.insertStudent(s);
        db.Disconnect();
    }
    
     //Listener and Adapter
    
    public void listenerStudentLogin(ActionListener AL){
        buttHomeStudent.addActionListener(AL);
        buttstudentLoginBackHome3.addActionListener(AL);
        buttstudentLoginToAdmin3.addActionListener(AL);
        buttstudentLogintoTentor3.addActionListener(AL);
    }
    
    public void resetView(){
        tf_studentRegName.setText("");
        tf_studentRegUsername.setText("");
        tf_studentRegPass.setText("");
        tf_studentRegID.setText("");    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttHomeStudent;
    private javax.swing.JButton buttstudentLoginBackHome3;
    private javax.swing.JButton buttstudentLoginToAdmin3;
    private javax.swing.JButton buttstudentLogintoTentor3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label lbALog4;
    private javax.swing.JTextField tf_studentRegID;
    private javax.swing.JTextField tf_studentRegName;
    private javax.swing.JPasswordField tf_studentRegPass;
    private javax.swing.JTextField tf_studentRegUsername;
    // End of variables declaration//GEN-END:variables
}
