/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class Student_Login extends javax.swing.JFrame {

    /**
     * Creates new form Student_Login
     */
    public Student_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        lbALog1 = new java.awt.Label();
        buttstudentLoginToAdmin = new javax.swing.JButton();
        buttStudentLogin = new javax.swing.JButton();
        buttstudentLogintoTentor = new javax.swing.JButton();
        tf_studentLogin1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttstudentLoginBackHome = new javax.swing.JButton();
        tf_studentLogin2 = new javax.swing.JPasswordField();
        buttHomeStudent1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Login Page E-Learning System ");

        jPanel2.setBackground(new java.awt.Color(31, 40, 51));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        lbALog1.setAlignment(java.awt.Label.CENTER);
        lbALog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog1.setForeground(new java.awt.Color(255, 153, 0));
        lbALog1.setText("Selamat Datang Mahasiswa");

        buttstudentLoginToAdmin.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLoginToAdmin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLoginToAdmin.setText("ADMIN");
        buttstudentLoginToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLoginToAdminActionPerformed(evt);
            }
        });

        buttStudentLogin.setBackground(new java.awt.Color(204, 204, 204));
        buttStudentLogin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttStudentLogin.setText("LOGIN");
        buttStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttStudentLoginActionPerformed(evt);
            }
        });

        buttstudentLogintoTentor.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLogintoTentor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLogintoTentor.setText("DOSEN");
        buttstudentLogintoTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLogintoTentorActionPerformed(evt);
            }
        });

        tf_studentLogin1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_studentLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_studentLogin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("USERNAME ");

        buttstudentLoginBackHome.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLoginBackHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLoginBackHome.setText("HOME");
        buttstudentLoginBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLoginBackHomeActionPerformed(evt);
            }
        });

        tf_studentLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_studentLogin2ActionPerformed(evt);
            }
        });

        buttHomeStudent1.setBackground(new java.awt.Color(204, 204, 204));
        buttHomeStudent1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttHomeStudent1.setText("SIGN UP");
        buttHomeStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHomeStudent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_studentLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttHomeStudent1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_studentLogin2))))
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttstudentLogintoTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttstudentLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(buttstudentLoginToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_studentLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tf_studentLogin2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttStudentLogin)
                    .addComponent(buttHomeStudent1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttstudentLogintoTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttstudentLoginToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttstudentLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttstudentLoginToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLoginToAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLoginToAdminActionPerformed

    private void buttStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttStudentLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttStudentLoginActionPerformed

    private void buttstudentLogintoTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLogintoTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLogintoTentorActionPerformed

    private void tf_studentLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_studentLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_studentLogin1ActionPerformed

    private void buttstudentLoginBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLoginBackHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLoginBackHomeActionPerformed

    private void tf_studentLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_studentLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_studentLogin2ActionPerformed

    private void buttHomeStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHomeStudent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttHomeStudent1ActionPerformed

  //get Button
    
    public JButton getbuttStudentLogin(){
        return buttStudentLogin;
    }
    public JButton getbuttstudentLoginBackHome(){
        return buttstudentLoginBackHome;
    }
    public JButton getbuttstudentLoginToAdmin(){
        return buttstudentLoginToAdmin;
    }
    public JButton getbuttstudentLogintoTentor(){
        return buttstudentLogintoTentor;
    }
    
    public JButton getbuttSignStudent(){
        return buttHomeStudent1;
    }
    
    //get Text
    public String gettf_studentLogin1(){
        return tf_studentLogin1.getText();
    }
    public String gettf_studentLogin2(){
        return tf_studentLogin2.getText();
    }
    
    //Listener and Adapter
    
    public void listenerStudentLogin(ActionListener AL){
        buttStudentLogin.addActionListener(AL);
        buttstudentLoginBackHome.addActionListener(AL);
        buttstudentLoginToAdmin.addActionListener(AL);
        buttstudentLogintoTentor.addActionListener(AL);
        buttHomeStudent1.addActionListener(AL);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttHomeStudent1;
    private javax.swing.JButton buttStudentLogin;
    private javax.swing.JButton buttstudentLoginBackHome;
    private javax.swing.JButton buttstudentLoginToAdmin;
    private javax.swing.JButton buttstudentLogintoTentor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label lbALog1;
    private javax.swing.JTextField tf_studentLogin1;
    private javax.swing.JPasswordField tf_studentLogin2;
    // End of variables declaration//GEN-END:variables
}
