/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Database.Database;
import eLearning.Tentor;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Asus
 */
public class Tentor_register extends javax.swing.JFrame {

    /**
     * Creates new form Tentor_register
     */
    public Tentor_register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        lbALog4 = new java.awt.Label();
        buttTentorLoginToMahasiswa = new javax.swing.JButton();
        butttentorLogintoAdmin = new javax.swing.JButton();
        tf_tentorRegUsername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butttentorLoginBackHome = new javax.swing.JButton();
        buttTentorSignUp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_tentorRegPass = new javax.swing.JPasswordField();
        tf_tentorRegID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_tentorRegName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Login Page E-Learning System ");

        jPanel5.setBackground(new java.awt.Color(31, 40, 51));
        jPanel5.setForeground(new java.awt.Color(255, 204, 0));

        lbALog4.setAlignment(java.awt.Label.CENTER);
        lbALog4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog4.setForeground(new java.awt.Color(255, 153, 0));
        lbALog4.setText("Registrasi Tentor");

        buttTentorLoginToMahasiswa.setBackground(new java.awt.Color(204, 204, 204));
        buttTentorLoginToMahasiswa.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttTentorLoginToMahasiswa.setText("MAHASISWA");
        buttTentorLoginToMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttTentorLoginToMahasiswaActionPerformed(evt);
            }
        });

        butttentorLogintoAdmin.setBackground(new java.awt.Color(204, 204, 204));
        butttentorLogintoAdmin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        butttentorLogintoAdmin.setText("ADMIN");
        butttentorLogintoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttentorLogintoAdminActionPerformed(evt);
            }
        });

        tf_tentorRegUsername.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_tentorRegUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tentorRegUsernameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("PASSWORD");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("USERNAME ");

        butttentorLoginBackHome.setBackground(new java.awt.Color(204, 204, 204));
        butttentorLoginBackHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        butttentorLoginBackHome.setText("HOME");
        butttentorLoginBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttentorLoginBackHomeActionPerformed(evt);
            }
        });

        buttTentorSignUp.setBackground(new java.awt.Color(204, 204, 204));
        buttTentorSignUp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttTentorSignUp.setText("SIGN UP");
        buttTentorSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttTentorSignUpActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("NAMA ");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("ID TENTOR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(butttentorLogintoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(butttentorLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(buttTentorLoginToMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lbALog4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tentorRegPass))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttTentorSignUp)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_tentorRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tentorRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_tentorRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(189, 189, 189))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbALog4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tentorRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tentorRegID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tentorRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tentorRegPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttTentorSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butttentorLogintoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttTentorLoginToMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butttentorLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttTentorLoginToMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttTentorLoginToMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttTentorLoginToMahasiswaActionPerformed

    private void butttentorLogintoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttentorLogintoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butttentorLogintoAdminActionPerformed

    private void tf_tentorRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tentorRegUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tentorRegUsernameActionPerformed

    private void butttentorLoginBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttentorLoginBackHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butttentorLoginBackHomeActionPerformed

    private void buttTentorSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttTentorSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttTentorSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    //get Button
    public JButton getbuttTentorSignUp(){
        return buttTentorSignUp;
    }
    public JButton getbuttTentorLoginToMahasiswa(){
        return buttTentorLoginToMahasiswa;
    }
    public JButton getbutttentorLoginBackHome(){
        return butttentorLoginBackHome;
    }
    public JButton getbutttentorLoginBackAdmin(){
        return butttentorLogintoAdmin;
    }
    
    //get Text
    public String gettf_tentorRegName(){
        return tf_tentorRegName.getText();
    }
    public String gettf_tentorRegID(){
        return tf_tentorRegID.getText();
    }
    public String gettf_tentorRegUsername(){
        return tf_tentorRegUsername.getText();
    }
    public String gettf_tentorRegPass(){
        return tf_tentorRegPass.getText();
    }
    
     //Listener and Adapter
    
    public void listenerTentorRegister(ActionListener AL){
        buttTentorSignUp.addActionListener(AL);
        butttentorLoginBackHome.addActionListener(AL);
        buttTentorLoginToMahasiswa.addActionListener(AL);
        butttentorLogintoAdmin.addActionListener(AL);
    }
    
    public void daftarTentor(){

        Database db = new Database();
        db.connect();
        String name = gettf_tentorRegName();
        int umur = 0;
        String id = gettf_tentorRegID();
        String uname = gettf_tentorRegUsername();
        String pass = gettf_tentorRegPass();
        Tentor s = new Tentor(name,id,umur,uname,pass);
        db.insertTentor(s);
        db.Disconnect();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttTentorLoginToMahasiswa;
    private javax.swing.JButton buttTentorSignUp;
    private javax.swing.JButton butttentorLoginBackHome;
    private javax.swing.JButton butttentorLogintoAdmin;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel5;
    private java.awt.Label label1;
    private java.awt.Label lbALog4;
    private javax.swing.JTextField tf_tentorRegID;
    private javax.swing.JTextField tf_tentorRegName;
    private javax.swing.JPasswordField tf_tentorRegPass;
    private javax.swing.JTextField tf_tentorRegUsername;
    // End of variables declaration//GEN-END:variables
}
