/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author user
 */
public class Tentor_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tentor_Login
     */
    public Tentor_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        lbALog1 = new java.awt.Label();
        butttentorLogintoStudent = new javax.swing.JButton();
        buttLoginTentor = new javax.swing.JButton();
        butttentorLogintoAdmin = new javax.swing.JButton();
        tf_tentorLogin1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        butttentorLoginBackHome = new javax.swing.JButton();
        tf_tentorLogin2 = new javax.swing.JPasswordField();
        buttSignupTentor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(11, 12, 16));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("Login Page E-Learning System ");

        jPanel2.setBackground(new java.awt.Color(31, 40, 51));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        lbALog1.setAlignment(java.awt.Label.CENTER);
        lbALog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog1.setForeground(new java.awt.Color(255, 153, 0));
        lbALog1.setText("Selamat Datang Dosen");

        butttentorLogintoStudent.setBackground(new java.awt.Color(204, 204, 204));
        butttentorLogintoStudent.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        butttentorLogintoStudent.setText("MAHASISWA");
        butttentorLogintoStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttentorLogintoStudentActionPerformed(evt);
            }
        });

        buttLoginTentor.setBackground(new java.awt.Color(204, 204, 204));
        buttLoginTentor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttLoginTentor.setText("LOGIN");
        buttLoginTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLoginTentorActionPerformed(evt);
            }
        });

        butttentorLogintoAdmin.setBackground(new java.awt.Color(204, 204, 204));
        butttentorLogintoAdmin.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        butttentorLogintoAdmin.setText("ADMIN");
        butttentorLogintoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttentorLogintoAdminActionPerformed(evt);
            }
        });

        tf_tentorLogin1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_tentorLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tentorLogin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("USERNAME ");

        butttentorLoginBackHome.setBackground(new java.awt.Color(204, 204, 204));
        butttentorLoginBackHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        butttentorLoginBackHome.setText("HOME");
        butttentorLoginBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttentorLoginBackHomeActionPerformed(evt);
            }
        });

        buttSignupTentor.setBackground(new java.awt.Color(204, 204, 204));
        buttSignupTentor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttSignupTentor.setText("SIGN UP");
        buttSignupTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSignupTentorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(butttentorLogintoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(butttentorLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(butttentorLogintoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttSignupTentor)
                                .addGap(46, 46, 46)
                                .addComponent(buttLoginTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_tentorLogin2)
                                    .addComponent(tf_tentorLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbALog1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tentorLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tentorLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttLoginTentor)
                    .addComponent(buttSignupTentor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butttentorLogintoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butttentorLogintoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butttentorLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butttentorLogintoStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttentorLogintoStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butttentorLogintoStudentActionPerformed

    private void buttLoginTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLoginTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttLoginTentorActionPerformed

    private void butttentorLogintoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttentorLogintoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butttentorLogintoAdminActionPerformed

    private void tf_tentorLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tentorLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tentorLogin1ActionPerformed

    private void butttentorLoginBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttentorLoginBackHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butttentorLoginBackHomeActionPerformed

    private void buttSignupTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSignupTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttSignupTentorActionPerformed

  //get Button
    public JButton getbutttentorLoginBackHome(){
        return butttentorLoginBackHome;
    }
    public JButton getbutttentorLogintoAdmin(){
        return butttentorLogintoAdmin;
    }
    public JButton getbutttentorLogintoStudent(){
        return butttentorLogintoStudent;
    }
    public JButton getbuttLoginTentor(){
        return buttLoginTentor;
    }
    public JButton getbuttSignupTentor(){
        return buttSignupTentor;
    }
    
   //get Text
    public String gettf_tentorLogin1(){
        return tf_tentorLogin1.getText();
    }
    public String gettf_tentorLogin2(){
        return tf_tentorLogin2.getText();
    }
    
    //Listener and Adapter
    
    public void listenerTentorLogin(ActionListener AL){
        buttLoginTentor.addActionListener(AL);
        butttentorLoginBackHome.addActionListener(AL);
        butttentorLogintoAdmin.addActionListener(AL);
        butttentorLogintoStudent.addActionListener(AL);
        buttSignupTentor.addActionListener(AL);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttLoginTentor;
    private javax.swing.JButton buttSignupTentor;
    private javax.swing.JButton butttentorLoginBackHome;
    private javax.swing.JButton butttentorLogintoAdmin;
    private javax.swing.JButton butttentorLogintoStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label lbALog1;
    private javax.swing.JTextField tf_tentorLogin1;
    private javax.swing.JPasswordField tf_tentorLogin2;
    // End of variables declaration//GEN-END:variables
}
