/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import eLearning.Kelas;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Tentor_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Tentor_Menu
     */
    public Tentor_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttstudentLoginBackHome = new javax.swing.JButton();
        label3 = new java.awt.Label();
        lbALog5 = new java.awt.Label();
        buttonLihatKelasDanStudent = new javax.swing.JButton();
        buttonUbahDataDiri = new javax.swing.JButton();
        lbALog6 = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelIDKelas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMateri = new javax.swing.JTable();
        buttTampilData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 40, 51));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        buttstudentLoginBackHome.setBackground(new java.awt.Color(204, 204, 204));
        buttstudentLoginBackHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        buttstudentLoginBackHome.setText("HOME");
        buttstudentLoginBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttstudentLoginBackHomeActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(11, 12, 16));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 153, 0));
        label3.setText("Tentor Page E-Learning System ");

        lbALog5.setAlignment(java.awt.Label.CENTER);
        lbALog5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog5.setForeground(new java.awt.Color(255, 153, 0));
        lbALog5.setText("Menu Tentor");

        buttonLihatKelasDanStudent.setBackground(new java.awt.Color(204, 204, 204));
        buttonLihatKelasDanStudent.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        buttonLihatKelasDanStudent.setForeground(new java.awt.Color(31, 40, 51));
        buttonLihatKelasDanStudent.setText("Kelas dan Student");
        buttonLihatKelasDanStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLihatKelasDanStudentActionPerformed(evt);
            }
        });

        buttonUbahDataDiri.setBackground(new java.awt.Color(204, 204, 204));
        buttonUbahDataDiri.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        buttonUbahDataDiri.setForeground(new java.awt.Color(31, 40, 51));
        buttonUbahDataDiri.setText(" Ubah Data Diri");
        buttonUbahDataDiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahDataDiriActionPerformed(evt);
            }
        });

        lbALog6.setAlignment(java.awt.Label.CENTER);
        lbALog6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbALog6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lbALog6.setForeground(new java.awt.Color(255, 153, 0));
        lbALog6.setText("Kelas Dan Materi");

        tabelIDKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA KELAS"
            }
        ));
        jScrollPane4.setViewportView(tabelIDKelas);

        tabelMateri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materi", "ID Materi"
            }
        ));
        jScrollPane2.setViewportView(tabelMateri);

        buttTampilData.setBackground(new java.awt.Color(204, 204, 204));
        buttTampilData.setText("Tampil");
        buttTampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttTampilDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttstudentLoginBackHome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttTampilData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonLihatKelasDanStudent)
                                    .addComponent(buttonUbahDataDiri, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lbALog5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbALog6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbALog5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbALog6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonUbahDataDiri)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLihatKelasDanStudent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttTampilData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(buttstudentLoginBackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttstudentLoginBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttstudentLoginBackHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttstudentLoginBackHomeActionPerformed

    private void buttonLihatKelasDanStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLihatKelasDanStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLihatKelasDanStudentActionPerformed

    private void buttonUbahDataDiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahDataDiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUbahDataDiriActionPerformed

    private void buttTampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttTampilDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttTampilDataActionPerformed

    //JButton 
    
    public JButton getButtonLihatKelasDanStudent() {
        return buttonLihatKelasDanStudent;
    }

    public JButton getButtonUbahDataDiri() {
        return buttonUbahDataDiri;
    }

    public JButton getButtstudentLoginBackHome() {
        return buttstudentLoginBackHome;
    }

    public JButton getButtTampilData() {
        return buttTampilData;
    }
        
    //Listener 
    public void addActionListener(ActionListener AL){
        buttonLihatKelasDanStudent.addActionListener(AL);
        buttonUbahDataDiri.addActionListener(AL);
        buttstudentLoginBackHome.addActionListener(AL);
        buttTampilData.addActionListener(AL);
    }
    
    public void addMouseAdapter(MouseAdapter ma){
        tabelMateri.addMouseListener(ma);
        tabelIDKelas.addMouseListener(ma);
    }
    
    public void setCRUDMateri(DefaultTableModel tabel)
    {
        tabelMateri.setModel(tabel);
    }
    public int getSelectedKelas()
    {
        return tabelMateri.getSelectedRow();
    }

    public JTable getTabelKelas() {
        return tabelMateri;
    }
    
    public void setTableIDKelas(DefaultTableModel tabel)
    {
        tabelIDKelas.setModel(tabel);
    }
    public int getSelectedIDKelas()
    {
        return tabelIDKelas.getSelectedRow();
    }

    public JTable getTabelIDKelas() {
        return tabelIDKelas;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttTampilData;
    private javax.swing.JButton buttonLihatKelasDanStudent;
    private javax.swing.JButton buttonUbahDataDiri;
    private javax.swing.JButton buttstudentLoginBackHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label3;
    private java.awt.Label lbALog5;
    private java.awt.Label lbALog6;
    private javax.swing.JTable tabelIDKelas;
    private javax.swing.JTable tabelMateri;
    // End of variables declaration//GEN-END:variables
}
